---
- name: Create folder
  hosts: ec2
  gather_facts: false
  
  tasks:
    - name: Create folder
      file: 
        path: ~/Ex2
        state: directory
        mode: "777"
    - name: find ~/ files 
      ansible.builtin.find:
        paths: ~/
