---
- name: Create folder
  hosts: localhost
  gather_facts: false
  
  tasks:
   - name: Create folder
     file: 
       path: /Users/deepthi/Documents/hello
       state: directory
       mode: "777"
