---
- name: to install a list of packages using list
  hosts: ec2
  gather_facts: true
  become: true

  vars:
    packages:
      - docker
      - nginx
      - telnet
      # - java-1.8.0-openjdk

  tasks:
    - name: install packages
      package:
        name: "{{ packages }}"
        state: present
