---
- name: Verify apache installation
  hosts: ec2
  become: true
  gather_facts: true

  tasks:
    - name: to install the package
      package:
        name: httpd
        state: present
      notify:
        - Restart service
  handlers:
    - name: Restart service
      ansible.builtin.service:
        name: httpd
        state: started
