---
name: Notify and Handler example
host: localhost
become: true

tasks:
  - name: to install the package
    package:
      name: telnet
      state: present
    notify: 
      - Restart service
handlers:
  - name: Restart service
    ansible.builtin.service:
      name: telnet
      state: started
