- name: Create folder
  hosts: ec2
  gather_facts: false
  become: true
  tasks:
    - name: Install the latest version of Apache
      ansible.builtin.yum:
        name: httpd
        state: latest
      when: ansible_distribution == 'amazon'

    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: httpd
        state: started
